# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-20 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0004_remove_shows_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='date',
            field=models.DateField(),
        ),
    ]
